### ISSUE TITLE
Play Console demands updated Target API level = 28 by November

### ISSUE THREAD

**Issue by jhugman** [mozilla-lockwise/lockwise-android#886] opened 2019-08-22 15:38 UTC
```
Target API level requirements from August 2019

Warning:

Your app currently targets API level 26 and must target at least API level 28 to ensure it is built on the latest APIs optimized for security and performance.

From August 2019, new apps must target at least Android 9.0 (API level 28).
From November 2019, app updates must target Android 9.0 (API level 28).
```

**Comment by devinreams** [comment] 2019-08-22 16:36
Duplicate of #148

**Comment by devinreams** [comment] 2019-08-22 16:37
Duplicate of #768

**Closed** 2019-09-23 15:41 UTC
Labels: closed-duplicate, type: task
