### ISSUE TITLE
Ability to create logins directly from the mobile app. 

### ISSUE THREAD

**Issue by no-good-usernames-left** [mozilla-lockwise/lockwise-android#839] opened 2019-07-24 13:34 UTC
### Why/User Benefit/User Problem
Benefits include not having to use into firefox on the computer to capture all login information, sync, and then wait for it to show up on the mobile app. 

Just enter it in directly in the app, that is what my family is looking for. 

### Acceptance Criteria (how do I know when I’m done?)
Expected workflow to be like 1Pass or Dashlane to create passwords and then sync securely between devices (In this case, Android and a Chromebook) for viewing and editing as needed for a reference.

**Comment by eliserichards** [comment] 2019-07-24 22:30
Closing this as duplicate of our `Create` milestones :) (Ex: #821)

**Closed by eliserichards** 2019-07-24 22:30 UTC
Labels: closed-duplicate, feature
