### ISSUE TITLE
Cannot input password to login to Firefox Account

### ISSUE THREAD

**Issue by masayuki-nakano** [mozilla-lockwise/lockwise-android#832] opened 2019-07-16 02:48 UTC
## Steps to reproduce
1. Launch Lockwise and tap Get Started
2. Input email address
3. Press continue button
4. Set focus to the password field with a tap

### Expected behavior
Can type password or paste password

### Actual behavior
Software keyboard showing only a second, then, throbber appeared and the email form.

I can reproduce this with either Gboard or ATOK (Japanese IME). Floating keyboard setting does not help to avoid this.

### Device & build information
* Device: Google Pixel 3a
* Build version: Not sure, I cannot access any information from the start screen.
### Notes
Attachments:

**Comment by IlgazC** [comment] 2019-07-16 15:08
Nokia 5.1 plus running current Android 9 with Google keyboard.  Same behaviour. Build version: 1.1.2 (4405)

**Comment by yuvalwolf** [comment] 2019-07-16 15:09
Do this behavior persist if you clear the app cache?

**Comment by yuvalwolf** [comment] 2019-07-16 15:17
Related to #798

**Comment by IlgazC** [comment] 2019-07-16 15:34
Cache cleared, it still happens. Actually email field acts strange too, hiding keyboard first and redisplaying.

**Comment by abodea** [comment] 2019-07-17 08:12
Hi @masayuki-nakano and thanks for this report.
## I tried to reproduce this issue, here is my input:
I tried to connect to lockwise latest version from **`Play Store`** but I was able to add the password every single time.
I used all the keyboards you mentioned [here](https://github.com/mozilla-lockwise/lockwise-android/issues/832#issue-468419554).
I tried with the exact steps and also I connected a hardware keyboard to the devices and still no issue.

I used the following devices: **`Google Pixel 3a XL(Android 9), Google Pixel 3a(Android 9), Samsung Galaxy S10+(Android 9).`**
The keyboard was displayed all the time out of at least 30 tries.

#### Can you provide the following information?
- The email you are trying to connect, is working on FF for android?
- Do you have other apps installed that might affect your keyboard?
- Can you verify this on any other device with your account?
- Can you provide a logcat for the exact moment when you reproduce the issue?
- Can you verify any keyboard you have in Play Store, maybe there is a update.
 - Any other info that can help us please mention them.

#### Also, try this:
 - Force kill lockwise.
 - Clear cache.
 - Uninstall lockwise.
 - Re-install Lockwise.
 - Login.

**Comment by masayuki-nakano** [comment] 2019-07-17 13:47
> I tried to connect to lockwise latest version from **`Play Store`** but I was able to add the password every single time.
> I used all the keyboards you mentioned [here](https://github.com/mozilla-lockwise/lockwise-android/issues/832#issue-468419554).
> I tried with the exact steps and also I connected a hardware keyboard to the devices and still no issue.
> 
> I used the following devices: **`Google Pixel 3a XL(Android 9), Google Pixel 3a(Android 9), Samsung Galaxy S10+(Android 9).`**
> The keyboard was displayed all the time out of at least 30 tries.

Hmm, that's really surprised.

> #### Can you provide the following information?
> 
>     * The email you are trying to connect, is working on FF for android?

Yes. And even when the email form is shown, every time the form is (looks like) reloaded once.

>     * Do you have other apps installed that might affect your keyboard?

I'm not sure. My language is Japanese.

>     * Can you verify this on any other device with your account?

Yes, with Zenfone5 (Android 9), I don't reproduce this.

>     * Can you provide a logcat for the exact moment when you reproduce the issue?

Hmm, I don't have much time for now due to skyline...

>     * Can you verify any keyboard you have in Play Store, maybe there is a update.

Sure, but I don't have much time for now.

>     * Any other info that can help us please mention them.

* Looks like that scroll or reflow causes the reloading.
* I don't connect physical keyboard, but I'll try it.

**Comment by IlgazC** [comment] 2019-07-17 17:24
Strangest thing ever. I have uninstalled Firefox Lockwise using Google Play Store "Uninstall" button. Installed again and I can't reproduce the issue either. App version 1.1.2 (4405). Now it works perfectly.

This is a brand new handset with no kind of root/hacks applied. Actually Lockwise installed freshly to a freshly purchased device with no data using Google's play functionality. While it isn't pure as a Google Pixel, it doesn't run any visible modifications, it is in "Android One" program if it matters. It runs Google Keyboard by default.

Only thing that seems strange to me is Google Webview was disabled in factory and Google Chrome is used to render pages. As far as I know "Lockwise" currently uses built-in OS HTML renderer.

**Comment by IlgazC** [comment] 2019-07-18 19:07
I have managed to retrigger the issue this time entering text to search field. Same issue happens, trying to enter "Facebook" to search field, keyboard disappeared and the following appears on logcat:

Cannot route from mozilla.lockbox:id/fragment_filter to mozilla.lockbox:id/fragment_item_list. This is a developer bug, fixable by adding an action to mozilla.lockbox:id/graph_main.xml and/or v

**Comment by simonsimon006** [comment] 2019-07-21 07:11
I have the same issue. I "solved" it by disabling Lockwise as autofill service in the android settings. Then I could login without problems and reenable it.

LG G8S
Android 9

**Comment by IlgazC** [comment] 2019-07-22 11:19
I have another Lineage device based on Android 9. I managed to get same issue on that device and it has more information in its logs. I am pasting relevant looking lines, I have the entire logs in zip file (personal details scrubbed) attached.

07-22 13:54:56.845 E/Lockwise(21209): Decrypt exception: 
07-22 13:54:56.845 E/Lockwise(21209): javax.crypto.AEADBadTagException
07-22 13:54:56.845 E/Lockwise(21209): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:517)
07-22 13:54:56.845 E/Lockwise(21209): 	at javax.crypto.Cipher.doFinal(Cipher.java:2055)
07-22 13:54:56.845 E/Lockwise(21209): 	at h.b.b.a.b.a(Keystore.kt:9)
07-22 13:54:56.845 E/Lockwise(21209): 	at h.c.i.w.a(SecurePreferences.kt:7)
07-22 13:54:56.845 E/Lockwise(21209): 	at mozilla.lockbox.LockboxAutofillService.onConnected(LockboxAutofillService.kt:9)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.service.autofill.-$$Lambda$amIBeR2CTPTUHkT8htLcarZmUYc.accept(Unknown Source:2)
07-22 13:54:56.845 E/Lockwise(21209): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.doInvoke(PooledLambdaImpl.java:244)
07-22 13:54:56.845 E/Lockwise(21209): 	at com.android.internal.util.function.pooled.PooledLambdaImpl.invoke(PooledLambdaImpl.java:182)
07-22 13:54:56.845 E/Lockwise(21209): 	at com.android.internal.util.function.pooled.OmniFunction.run(OmniFunction.java:77)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.os.Handler.handleCallback(Handler.java:873)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.os.Handler.dispatchMessage(Handler.java:99)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.os.Looper.loop(Looper.java:193)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.app.ActivityThread.main(ActivityThread.java:6718)
07-22 13:54:56.845 E/Lockwise(21209): 	at java.lang.reflect.Method.invoke(Native Method)
07-22 13:54:56.845 E/Lockwise(21209): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
07-22 13:54:56.845 E/Lockwise(21209): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
07-22 13:54:56.845 E/Lockwise(21209): Caused by: android.security.KeyStoreException: Signature/MAC verification failed
07-22 13:54:56.845 E/Lockwise(21209): 	at android.security.KeyStore.getKeyStoreException(KeyStore.java:839)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.security.keystore.KeyStoreCryptoOperationChunkedStreamer.doFinal(KeyStoreCryptoOperationChunkedStreamer.java:224)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.security.keystore.AndroidKeyStoreAuthenticatedAESCipherSpi$BufferAllOutputUntilDoFinalStreamer.doFinal(AndroidKeyStoreAuthenticatedAESCipherSpi.java:373)
07-22 13:54:56.845 E/Lockwise(21209): 	at android.security.keystore.AndroidKeyStoreCipherSpiBase.engineDoFinal(AndroidKeyStoreCipherSpiBase.java:506)
07-22 13:54:56.845 E/Lockwise(21209): 	... 15 more

[2019-07-22_14.02-lockwise.zip](https://github.com/mozilla-lockwise/lockwise-android/files/3416971/2019-07-22_14.02-lockwise.zip)

**Comment by klausenbusk** [comment] 2019-07-23 22:11
> I have the same issue. I "solved" it by disabling Lockwise as autofill service in the android settings. Then I could login without problems and reenable it.

I can confirm.

Samsung S4 Mini (Android Pie)

**Comment by masayuki-nakano** [comment] 2019-07-24 03:13
> > I have the same issue. I "solved" it by disabling Lockwise as autofill service in the android settings. Then I could login without problems and reenable it.
> 
> I can confirm.
> 
> Samsung S4 Mini (Android Pie)

Me too. Sounds like that Lockwise is not aware of autofill and/or using autofill in itself.

**Comment by eliserichards** [comment] 2019-07-24 22:33
Yikes! What an issue! Thanks for jumping in to look at this everyone, It's greatly appreciated 😄

**Comment by ddurst** [comment] 2019-08-09 15:24
Related to #798

**Comment by eliserichards** [comment] 2019-09-13 14:42
This has been mitigated by #890 (available in release 2.0.0). Closing as it is no longer valid.

**Closed by eliserichards** 2019-09-13 14:42 UTC
Labels: closed-duplicate, type: defect
