### ISSUE TITLE
"DataStore backend is not set" when using autofill in an app

### ISSUE THREAD

**Issue by ckarlof** [mozilla-lockwise/lockwise-android#531] opened 2019-03-23 17:23 UTC
I've seen this [error](https://github.com/mozilla-lockbox/lockbox-android/blob/67060bf4af4d28d59de51e9788cf56e3f2f463bd/app/src/main/java/mozilla/lockbox/store/DataStore.kt#L265) twice while trying to use autofill in an app (it shows in a little overlay near the bottom of the screen). When it try autofill again, I'm asked to unlock Lockbox, and after I do, I'm successful in autofilling. #464 or #275 might be related.

**Comment by aneutron** [comment] 2019-03-25 15:23
I think I may have an idea about the reason. I have an LG G6 and the battery saving mode is quite aggressive. Adding Lockbox to the exceptions solved the problem for me. I'll do further testing later.

**Comment by devinreams** [comment] 2019-03-27 15:32
May be a race condition, will try to reproduce.

May not be a straight forward after discussing with the team...

**Comment by pwd-github** [comment] 2019-04-08 13:25
I'm getting this quite a bit. It seems to happen when lockbox drops out of memory.

**Comment by lnicola** [comment] 2019-04-08 13:26
Disabling "Battery Optimization" for Lockbox fixed this on my OnePlus 6T.

**Comment by pwd-github** [comment] 2019-04-08 20:22
Sadly that's not fixed it on my device.

**Comment by devinreams** [comment] 2019-04-19 17:31
I'm still seeing this on the 1.0.2 beta but with no error/crash logged via Sentry.

- I let the app go to the background and lock
- Opened Netflix app
- Tapped sign in and into the field

Expected: show the autofill dropdown (or "Unlock Firefox Lockbox" prompt)
Actual: error toast "Datastore backend is not set"...

A workaround was I went to another application that I know autofill worked in:

- opened Instagram
- tapped into sign in field
- it showed the "Unlock Firefox Lockbox" message
- I unlocked and switched back to Netflix
- tapped into Netflix sign in field, it showed me the autofill dropdown

Then I opened Lockbox and manually "Lock Now"ed it to try and reproduce in Netflix again:

- tapped "Lock Now" in Lockbox
- opened Netflix
- opened sign in form
- tapped in and it showed me the "Unlock Firefox Lockbox" message
- after unlock, it showed my saved login ✅ 

So still sounds reasonable this is a race condition. 🤷‍♂️ 

Marking as P2 for now since there are seemingly some workarounds...

**Comment by gerdneuman** [comment] 2019-05-03 14:33
Came here after googling for this error.

Same Issue on Samsung Galaxy A3 (2017) when trying to use Firefox Nightly for Android. Current Version 1.02 and current Nightly. I've seen this error from the beginning of the 1.0 Lockbox release:
![signal-attachment-2019-05-03-163028](https://user-images.githubusercontent.com/12525563/57144317-1af6ac00-6dc1-11e9-8248-448c6dcdef5a.jpeg)

At least, the error message should be somewhat more useful so that one knows what's the real issue/cause here and workaround.

**Comment by nyetwurk** [comment] 2019-05-12 16:52
Disabling battery optimization does not fix the problem for me either

**Comment by strugee** [comment] 2019-05-13 05:13
> I'm getting this quite a bit. It seems to happen when lockbox drops out of memory.

I'm pretty sure this is it. I hit this basically every time I use Lockbox and I run some other memory-intense apps on my phone, which would mean Lockbox was getting evicted from memory very often. It also makes sense that battery optimization would help some people but not others, since it would stop it getting evicted from memory some of the time but wouldn't be a hard guarantee.

The workaround I use is to hit back, and then initiate the login again. Then I get the "Unlock Firefox Lockbox" message. This is consistent with the memory eviction theory:

1. Firefox Lockbox gets unloaded from memory by Android
2. I open a login form, Lockbox is loaded, and I get the exception this issue is about
3. I tap back
4. I open the login form again. Since Lockbox is now running, it works fine and this issue doesn't come up.

**Comment by lnicola** [comment] 2019-05-13 05:36
What I do is start Lockbox manually, then switch back to Firefox. It still happens sometimes, even though I disabled all the battery optimization options (there's about three of them on my phone). But I also have issues with other apps but showing notifications until I start them.

**Comment by kanru** [comment] 2019-05-28 22:35
I also hit this everyime on a Pixel 3. I used the same workaround "manually start the app before open the login form"

**Comment by leotsarev** [comment] 2019-05-29 20:28
Same for me everytime on mi a1

**Comment by strugee** [comment] 2019-05-30 00:30
Hey all - at this point it's clear that this bug exists, so we don't need any more comments confirming that it exists - what we need is an actual fix for the bug. (When I say "we" I mean people in this thread; I do not work or speak for Mozilla.) When you comment "me too", that just generates more email for people subscribed to this issue. I would suggest using GitHub's reactions feature to add a :thumbsup: reaction to the issue instead.

**Comment by pwd-github** [comment] 2019-05-31 08:56
This is still an issue in the latest build. I hoped it would've been fixed with the update of application services and Android Components, but no such luck.

Is the solution just to create a lowest priority notification to keep the service running?

**Comment by lynxlee** [comment] 2019-06-04 09:05
Using a Huawei, I had to go under Settings-->Battery-->App launch and change from Manage automatically to Manage manually for this to work.

**Comment by saks** [comment] 2019-06-04 19:05
I'm on lg v30, I get this error even after adding the app to the list of "Power saving exclusions".

**Comment by vfrico** [comment] 2019-06-06 07:10
I also have this problem on a BQ Aquaris X Pro.

I've just restored from factory settings and I get the same error. To help reproduce the error: I have installed also Firefox Beta on the device.

Disabling battery saving for this app does not change anything

**Closed** 2019-06-15 00:03 UTC
Labels: P2, bug, needs-reproduce, 💬 feature-autofill

**Comment by simonbcn** [comment] 2019-06-19 07:36
Done? Perhaps, but as long as it's not updated in the Google Play Store, it can't be verified.
