### ISSUE TITLE
datastore backend is not set

### ISSUE THREAD

**Issue by jigarashah** [mozilla-lockwise/lockwise-android#795] opened 2019-06-27 13:41 UTC
## Steps to reproduce
Open any application without first opening lockwise. Go to sign in screen. 
### Expected behavior
Should work
### Actual behavior
It crashes and gives prompt
### Device & build information
* Device: ? Samsung galaxy 8
* Build version: ? Android P. Lockwise latest.
### Notes
Attachments: 
![Screenshot_20190615-191134_goMF](https://user-images.githubusercontent.com/3633893/60271087-fb2bc200-98f1-11e9-89b3-0461462d116c.jpg)

**Comment by jigarshah** [comment] 2019-06-27 16:28
Duplicate of #531 which seems fixed. default search in github is open issue :)

**Comment by devinreams** [comment] 2019-06-27 16:38
Thanks @jigarashah, not a problem. Version 1.1.2, which is available to Beta testers and will be live to all users soon, should resolve this (I personally haven't encountered it again in my own testing).

Once you have the update, please let us know if it's still happening for you...

**Closed by devinreams** 2019-06-27 16:38 UTC
Labels: bug
