### ISSUE TITLE
New entry can be created with only "http:// or https://` in Web Address(without a real website)

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1134] opened 2020-01-13 13:45 UTC
## Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. On the entries, section tap on the `+` button in order to create a new entry.
4. Add the password and on the `Web Address` add only `https:// or http://`
5. Tap on the save button.
### Expected behavior
An error should be returned when trying to create a new entry without a real web address.
### Actual behavior
The account can be saved without problems.
### Device & build information
* Device: **Google Pixel 3a XL(Android 10).**
* Build version: **Latest master version 3.3.0 from 1/13.**
### Notes
The `https:// or http://` can be accessed without problems from the newly created entry.

**Comment by eliserichards** [comment] 2020-01-14 17:00
Closing as duplicate of #1131

**Closed by eliserichards** 2020-01-14 17:00 UTC
Labels: defect, feature-CUD
