### ISSUE TITLE
the app doesn't open

### ISSUE THREAD

**Issue by ghost** [mozilla-lockwise/lockwise-android#815] opened 2019-07-04 10:45 UTC
## Steps to reproduce
Me opening the app
### Expected behavior
The app loading
### Actual behavior
It says it could not start
### Device & build information
* Device: SM-T355Y
* Build version: Latest
### Notes
Attachments: 
  
![20190704_202849](https://user-images.githubusercontent.com/52532041/60661146-b0371f00-9e9c-11e9-9f8a-478a7bada875.jpg)

**Comment by eliserichards** [comment] 2019-07-24 22:43
Hi @Michael-1928! We will need a little bit more information in order to reproduce this: 
* Was this your first time starting the app?
* Did you make a new Firefox Account, or do you have an existing account?
* What version of android are you using?
* Did you install the app from Google Play Store or from source?

**Comment by AndiAJ** [comment] 2019-07-29 09:18
Hi @eliserichards, I've checked @Michael-1928 device ( **SM-T355Y**) and it seems to be a Galaxy Tab A (**Android v5.0 )** 
I've used a **SM-T365**  Galaxy Tab A (**Android 5.1.1 )** and couldn't install 1.1.3 (Build 4584) nor could find a build on Google Play.

Could this be happening because of the design? based on [this comment](https://github.com/mozilla-lockwise/lockwise-android/issues/512#issuecomment-475664368)

**Comment by Michael-1928** [comment] 2019-07-29 10:41
Hi @eliserichards, i am answering your questions

### 1. Was this your first time starting the app?
* No I have used it for a few months before it didn't work.

### 2. Did you make a new Firefox Account, or do you have an existing account?
* I had an existing account before the issue.

### 3. What version of android are you using?
* I am using android 7.1.1 .

### 4.  Did you install the app from Google Play Store or from source?
* I used both.

**Comment by abodea** [comment] 2020-02-18 12:26
Verified as fixed on the latest build **4.0.0 (Build 6087)** using Samsung Galaxy S7(Android 7).
Note that everything worked as expected.
Based on my comment I will remove the `needs-reproduce` and I will close this issue.
@ghost feel free to re-open the issue if this will occur to you again.

**Closed by abodea** 2020-02-18 12:26 UTC
Labels: crash, defect, needs-reproduce, question
