### ISSUE TITLE
Lockwise should cache access tokens

### ISSUE THREAD

**Issue by grigoryk** [mozilla-lockwise/lockwise-android#941] opened 2019-09-24 21:31 UTC
On startup (I think), `detectAccount` runs...
https://github.com/mozilla-lockwise/lockwise-android/blob/c435688538e54d309dbc94e74682c2904267363f/app/src/main/java/mozilla/lockbox/store/AccountStore.kt#L167
... and for existing users it requests a new access token.
https://github.com/mozilla-lockwise/lockwise-android/blob/c435688538e54d309dbc94e74682c2904267363f/app/src/main/java/mozilla/lockbox/store/AccountStore.kt#L197

Access tokens aren't part of the persisted FxA state. They are cached in memory by the Rust code, but in the startup scenario that cache is going to be empty.

This means that every startup of Lockwise will request a new access token, causing INSERTs in the FxA OAuth db.

We've addressed this problem in Fenix (via android-components AccountManager) by introducing a persistent caching layer (in sharedprefs) in a-c, which only requests new tokens if cached one have expired. See https://github.com/mozilla-mobile/android-components/pull/3579 for details on the problem and solution outline.

**Comment by grigoryk** [comment] 2019-09-24 21:53
In a-c, a helper class is exposed that could be used here - `SyncAuthInfoCache`. Lockwise seems to have re-wrapped a-c types though, so some type conversion will be necessary. Also, a-c class doesn't allow specifying storage backend, which in Lockwise would need to be `SecurePreferences.shared`.

**Comment by grigoryk** [comment] 2019-09-24 21:59
Or, let A-S do it as part of FxA state. https://github.com/mozilla/application-services/pull/1274 - with that PR in place (or similar), afaik no code changes would be necessary client-side.

**Comment by shane-tomlinson** [comment] 2019-09-25 08:19
cc @clouserw, @jrgm, and @jbuck since this has to do with the high access token write load.

Thanks for filing this @grigoryk.

**Comment by jhugman** [comment] 2019-09-26 11:38
`FxA` have asked lockwise to try and reduce the number of token requests, so add some amount of caching.

Waiting for  https://github.com/mozilla/application-services/pull/1274 to feed through android-components is:

 a) unlikely to happen soon enough 
 b) on its own won't fix the problem — it doesn't include token expiry and rotation.

Currently, token lifetime is about 1-3 days: not long enough to do without token rotation, but short enough that users will be affected.

**Closed** 2019-09-30 12:11 UTC
Labels: priority: P1, type: defect

**Comment by abodea** [comment] 2019-10-21 13:11
We re-checked this issue alongside with the #953 but everything worked as expected. No regressions and 0 crashes.
The `Invalid token` issue will be followed-up on the FxA repo and #953 will be closed as well.
Based on this comment I will set this issue as verified, and re-open it or a new one in case of any new issue.
