### ISSUE TITLE
Samsung devices: Auto-fill menu not displaying search.

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#614] opened 2019-04-23 09:47 UTC
### Steps to reproduce
1. Set up Lockbox as your autofill provider.
2. Open up Firefox.
3. Go to any page that has your credentials saved in Lockbox (eg. Facebook).
4. Tap on login and then in the username or password field.

### Expected behavior
Lockbox autofill options appear and you have the possibility to search.

### Actual behavior
There is no way to search. 

### Device and build information
- Samsung Galaxy S8 (Android 9)
- Samsung Galaxy Note 9 (Android 9)
- Lockbox version: 1.0.2 (3428) from Play Store

### Notes
- Not reproducible on a Pixel 3 XL.

![screen](https://user-images.githubusercontent.com/17178945/56571319-56c19280-65c5-11e9-9698-eeb5f9b21d11.png)

**Comment by devinreams** [comment] 2019-04-23 14:09
@bsurd does it appear if you scroll the long list of matching entries? It _should_ be anchored to the bottom of what's essentially a fixed-height scrolling list. 🤞

**Comment by bsurd** [comment] 2019-04-23 15:20
@devinreams Yes it does appear at the end, scrolled only halfway as there are quite a lot of entries.

**Comment by changecourse** [comment] 2019-04-23 15:27
@devinreams I still would consider this a design bug, as there is no real affordance to the user that there are more than three logins available in the dropdown... I'd want to either increase or decrease the height of the list, so we can partially expose the bottom login and improve usability here.

**Comment by eliserichards** [comment] 2019-09-18 02:26
Closing as a duplicate of #479

**Closed by eliserichards** 2019-09-18 02:26 UTC
Labels: type: defect
