### ISSUE TITLE
A white box/square is displayed when tapping and holding on the search text field

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#298] opened 2018-12-19 11:16 UTC
## Steps to reproduce
1. Open Lockbox.
2. Login with valid credentials.
3. Tap on search button.
4. Tap and hold on the text area in search menu.
### Expected behavior
The "Copy, Cut, Paste, Clipboard, Autofill" custom menu is displayed 
### Actual behavior
The "Copy, Cut, Paste, Clipboard, Autofill" custom menu is displayed with a large white box/square around
### Device and build information
* Firefox Lockbox version: 1.0([build #1785](https://app.bitrise.io/build/8d9b6261fed6330c))
* Google Pixel 3 XL (Android 9)
* Samsung Galaxy Note 9 (Android 8.1.0)
* Sony Xperia (Android 6)
### Notes
The search text field cannot be seen anymore as the white box/square is too big behind the custom menu on Samsung Galaxy Note 9 (Android 8.1.0), on the other devices, the box/square is smaller.
[Video](https://goo.gl/ZPXhLf)
[Logcat.txt](https://github.com/mozilla-lockbox/lockbox-android/files/2694531/Logcat.txt)

![bug](https://user-images.githubusercontent.com/42831109/50217063-4a67c780-0390-11e9-87a3-4e9fff76d924.jpg)

**Comment by pwd-github** [comment] 2019-03-30 21:40
I just came to report this, glad to see it's already here and thus I only need to confirm it.

**Comment by eliserichards** [comment] 2019-05-15 17:30
@eliserichards confirm if this is resolved.

**Comment by Diana-Rus** [comment] 2019-09-16 12:26
Hi @eliserichards , issue is still reproducible, verified with Google Pixel 3 XL (Android 9) and Samsung Galaxy S9 (Android 8) on Lockwise 2.0.0 ([Build 4824](https://github.com/mozilla-lockwise/lockwise-android/releases)).

**Comment by Diana-Rus** [comment] 2019-09-16 12:28
Based on my previous comment I will remove the "needs reproduce" label.

**Comment by changecourse** [comment] 2019-09-16 15:35
Also worth catching @eliserichards is the default green color on the selection arrow. 

FWIW, I was unable to reproduce on 2.0.0, Pixel 2 (Android 9)

**Comment by eliserichards** [comment] 2019-11-08 17:29
Fixed by #1036

**Closed by eliserichards** 2019-11-08 17:29 UTC
Labels: closed-duplicate, type: defect
