### ISSUE TITLE
Add Lockwise to Fdroid

### ISSUE THREAD

**Issue by ahangarha** [mozilla-lockwise/lockwise-android#1032] opened 2019-10-27 16:54 UTC
### Why/User Benefit/User Problem
As the most important repository for Free Software Android applications, this app should be available there.

Free Software deserves to be hosted on Free Software repository

**Comment by eliserichards** [comment] 2019-11-12 17:41
Duplicate of #416

**Closed by eliserichards** 2019-11-12 17:41 UTC
Labels: closed-duplicate, feature
