### ISSUE TITLE
App state reset when switching between apps

### ISSUE THREAD

**Issue by agi90** [mozilla-lockwise/lockwise-android#915] opened 2019-09-11 18:26 UTC
## Proposed Approach
Proposed solution is to tie the user's persistent state within the app to the autolock timer setting, so that toggling between apps maintains the user's location, within a given login detail, for instance, regardless of backgrounding and foregrounding the app. 

## Steps to reproduce
- Select a login item
- Switch to another app
- Come back to Lockwise

### Expected behavior
- The selected login item is visible

### Actual behavior
- Lockwise is back to the home page
### Device & build information
* Device: Samsung S10
* Build version: Latest from play store

**Comment by eliserichards** [comment] 2019-09-11 18:49
@sandysage @changecourse  - this is a suggested improvement on our current implementation. Any thoughts?

**Comment by changecourse** [comment] 2019-09-11 18:54
I agree that this would be valuable... initial thoughts would be that we'd need to have some logic or a timer in place... maintaining a given location within the app for a period of time, regardless of app switching, then reverting to our login list following a period of inactivity, tbd.

**Comment by changecourse** [comment] 2019-10-23 15:01
Thinking more about this, we should consider persisting the app state alongside the autolock setting, so that even when the app goes into the background, it maintains it's current screen... This will account for situations like @agi90 describes above, where toggling between apps (to manually copy/paste multiple credentials) would be possible, since the app would not 'reset' to the logins list until the app is locked. I also feel that aligning this with the autolock timer would make it somewhat intuitive, vs. considering some sort of arbitrary global time for persistence.

**Comment by jhugman** [comment] 2019-11-15 17:48
Duplicate of #987. Closing.

**Closed by jhugman** 2019-11-15 17:48 UTC
Labels: effort: M, feature, priority: P2, type: enhancement
