### ISSUE TITLE
Air View window has a big blue border 

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#302] opened 2018-12-19 15:48 UTC
## Steps to reproduce
1. Launch Lockbox and login with valid credentials.
2. Hover the S-Pen over the: "Search entries, Sort items, Menu, Back" buttons

### Expected behavior
The Air View window is correctly displayed and no residual / big borders are displayed.

### Actual behavior

The Air view window is displayed with a large blue border.

### Device information
Firefox Lockbox version: 1.0(build #1785)
Samsung Galaxy Note 9 (Android 8.1.0)

### Notes
This issue can be reproduce only with devices with S-Pen like Samsung Galaxy Note versions.
[Video](https://goo.gl/BURfqT)
[Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2695524/Logcat.txt)

**Comment by eliserichards** [comment] 2019-09-13 17:37
Closing as a duplicate of #298.

**Closed by eliserichards** 2019-09-13 17:37 UTC
Labels: closed-duplicate, type: defect
