### ISSUE TITLE
"Unlock Firefox Lockwise" popup hard to read when using dark theme

### ISSUE THREAD

**Issue by pocmo** [mozilla-lockwise/lockwise-android#1109] opened 2019-12-11 19:36 UTC
When using Fenix in dark mode then the "Unlock Firefox Lockwise" message is hard to read (black text on dark gray). After unlocking Lockwise the list of accounts is readable though (black text on white).

* Device: Pixel 3
* Build version: 3.3.0

![Screenshot_20191211-180151](https://user-images.githubusercontent.com/89638/70653994-c324fb00-1c55-11ea-946a-768669908191.png)

**Comment by abodea** [comment] 2019-12-17 14:25
Thank you for adding this issue @pocmo.
I will close it as a dupe of #1072.

**Closed by abodea** 2019-12-17 14:25 UTC
