### ISSUE TITLE
Add animation when selecting an account in the main menu section

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1169] opened 2020-02-17 15:03 UTC
### Why/User Benefit/User Problem
As a Lockwise user, I wanna see exactly what account I'm selecting before accessing it.
### Acceptance Criteria (how do I know when I’m done?)
When selecting an account, there will be an animation.
### Notes
Similar animation like it's in settings menu can be added for the accounts.

**Comment by eliserichards** [comment] 2020-02-18 22:13
Closing as dupe of #1172

**Closed by eliserichards** 2020-02-18 22:13 UTC
Labels: closed-duplicate, enhancement
