### ISSUE TITLE
Lockwise logo is flashing when resuming Lockwise while being in "You're all set!" screen

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#697] opened 2019-05-24 09:13 UTC
### Steps to reproduce
1. Launch lockwise.
2. Login with valid credentials.
3. When reaching **`You're all set!`** put lockwise in the background.
4. Resume lockwise.
### Expected behavior
Lockwise is resumed and no display issues are present.
### Actual behavior
When resuming lockwise, the lockwise logo is displayed right in the middle of the **`You're all set!`** screen.
### Device and build information
* **`Google Pixel 3(Android 9)`**
*  **`Lockbox version: 1.1.0 (3951)`**
### Notes 
This issue can be reproduced on any device, for more details please see the attachments: [video](https://drive.google.com/file/d/1YF9Q6FsuSjphfrjqwDs93r1fE-1cKfVW/view?usp=sharing).

**Comment by eliserichards** [comment] 2019-05-24 16:35
Duplicate of #673.

**Closed** 2019-05-28 21:21 UTC
Labels: bug
