### ISSUE TITLE
Can't start app after changing the Firefox account password

### ISSUE THREAD

**Issue by limonte** [mozilla-lockwise/lockwise-android#770] opened 2019-06-24 19:45 UTC
I just lost all my passwords (https://github.com/mozilla-lockwise/lockwise-addon/issues/327) but that's mostly related to the lockwise browser addon, what is relevant here is that I can't open my Android app after changing the Firefox account password

## Steps to reproduce

1. Have browser extension + Android device syncronized
2. Change password from Firefox account
3. Try to open Android app

### Expected behavior

It works.

### Actual behavior

It stucks on the white screen with the Firefox Lockwise logo:

![image](https://user-images.githubusercontent.com/6059356/60047183-bde8e980-96d1-11e9-9ea8-ac4169b68307.png)

**Comment by eliserichards** [comment] 2019-09-18 03:43
Related to #753.

**Comment by eliserichards** [comment] 2019-09-18 03:43
Closing as duplicate of #753

**Closed by eliserichards** 2019-09-18 03:43 UTC
Labels: feature-sync ♻️, type: defect
