### ISSUE TITLE
After unlocking the app user has empty state and has to wait for "Syncing" instead of seeing existing entries

### ISSUE THREAD

**Issue by bsurd** [mozilla-lockwise/lockwise-android#360] opened 2019-01-09 10:33 UTC
## Steps to reproduce
1. Open Lockbox and log in with a valid account.
2. Open the Menu and tap on Lock Now (set screen lock if needed).
3. Tap on Unlock.

### Expected behaviour
Initial synced entries are still displayed, sync is performed only for new entries.

### Actual behaviour
No synced entries are displayed after unlock, user is greeted with an empty list, entries appearing after a few seconds.

### Device and build information
- Sony Xperia Z5 Premium (Android 7.1.1)
- Samsung Galaxy S8 (Android 8)
- Google Pixel (Android 9)
- [Build #2068](https://app.bitrise.io/build/5de084abff2a9e31)

### Notes
- Search icon is also disabled while the the list is populated
- [Logcat](https://github.com/mozilla-lockbox/lockbox-android/files/2740431/log.txt)

**Comment by devinreams** [comment] 2019-01-09 20:05
@bsurd have you experienced this _only_ on that initial launch-and-login. Or other times?

I _think_ in my own testing I've encountered this during first run only and my workaround has been to force quit the app and re-open.

**Comment by bsurd** [comment] 2019-01-10 13:58
Each time I've unlocked the app as mentioned in the issue descriprion.

**Comment by devinreams** [comment] 2019-01-23 21:34
Please correct me if wrong, but I believe this describes the fact an empty screen appears with no entries and no indicator that syncing is occurring (#388). Having no entries and needing to show "Syncing..." is expected during a first run experience...

When a user opens the app after _any_ sync has happened in the past, I think we should expect some of the data to be cached on device and not show a fully empty/cleared out list of items.

**Comment by linuxwolf** [comment] 2019-02-08 17:59
I suspect this behavior no longer happens, and instead you get the behavior from #415 

I further suspect it is related to our backends never really getting to the unlocked state:

```
-----BEGIN UNLOCKED-----
2019-02-08 10:41:11.572 6950-6950/mozilla.lockbox D/Log: TRACKING ApplicationPresenter startup
2019-02-08 10:41:11.573 6950-6950/mozilla.lockbox D/Log: TRACKING Lifecycle next is Startup
2019-02-08 10:41:11.716 6950-6950/mozilla.lockbox D/Log: TRACKING AccountStore.profile next is test (whovian@tardis.net)
2019-02-08 10:41:11.717 6950-6950/mozilla.lockbox D/Log: TRACKING AccountStore.syncCredentials next is (new? false) (valid? true) 
2019-02-08 10:41:11.717 6950-6950/mozilla.lockbox D/Log: TRACKING AccountStore.syncCredentials starts as 
2019-02-08 10:41:11.717 6950-6950/mozilla.lockbox D/Log: TRACKING AccountStore.profile starts as test
2019-02-08 10:41:11.972 6950-6950/mozilla.lockbox D/Log: TRACKING ApplicationPresenter foreground
2019-02-08 10:41:11.972 6950-6950/mozilla.lockbox D/Log: TRACKING Lifecycle next is Foreground
2019-02-08 10:41:11.972 6950-6950/mozilla.lockbox D/Log: TRACKING AutoLockStore get autolock time as 51788553
2019-02-08 10:41:11.972 6950-6950/mozilla.lockbox D/Log: TRACKING AutoLockStore get system time as 51498456
2019-02-08 10:41:11.972 6950-6950/mozilla.lockbox D/Log: TRACKING AutoLockStore.autoLockActivated starts as false
-----END UNLOCKED-----

```

**Comment by sashei** [comment] 2019-02-15 18:20
I can't reproduce this after merging #435

**Comment by devinreams** [comment] 2019-02-15 20:52
I still get this behavior where instead of showing the entries I was _just looking at_ before locking/unlocking I get the placeholder empty/syncing toast screen.

I don't think this is a blocker/serious problem but it's a less desirable experience since the user has to sit and wait for entries to be fully re-loaded into the view instead of seeing the ones they already had before locking/unlocking..

I renamed the title to explain this fully and propose we downgrade this from a P1 to a 3 then consider if we want to re-prioritize with @mozilla-lockbox/product.

**Comment by eliserichards** [comment] 2019-09-13 21:32
Closing as this is no longer applicable.

**Closed by eliserichards** 2019-09-13 21:32 UTC
Labels: closed-invalid, priority: P3, type: defect
