### ISSUE TITLE
The text selection pointer/cursor has a blue background 

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#300] opened 2018-12-19 13:34 UTC
## Steps to reproduce
1. Open Lockbox.
2. Login with valid credentials.
3. Tap on search button.
4. Tap and hold on the text area in search menu.

### Expected behavior
The text selector pointer/bubble is correctly displayed

### Actual behavior

The text selector pointer/bubble has a blue background.

### Device and build information
* Firefox Lockbox version: 1.0([build #1785](https://app.bitrise.io/build/8d9b6261fed6330c))
* Google Pixel 3 XL (Android 9)
* Samsung Galaxy Note 9 (Android 8.1.0)
* Sony Xperia (Android 6)

### Notes
The text selector pointer/bubble should be only one color without any other background colors.
![screenshot_20181219-145350_firefox lockboxa](https://user-images.githubusercontent.com/42831109/50223229-42fde980-03a3-11e9-9f37-bf77f5df0727.jpg)

**Comment by sandysage** [comment] 2019-01-07 21:50
@nickbrandt I think we tested this in person and can't reproduce it on the Pixel 2. Is that correct?

**Comment by nickbrandt** [comment] 2019-01-07 22:15
@sandysage yes, though it was a Pixel 1 (running Android 9/Pie).

**Comment by eliserichards** [comment] 2019-05-15 17:31
@eliserichards confirm if this is resolved.

**Comment by eliserichards** [comment] 2019-09-13 17:34
Related to #298. Closing as duplicate in favor of that bug.

**Closed by eliserichards** 2019-09-13 17:34 UTC
Labels: closed-duplicate, type: defect
