### ISSUE TITLE
No entries found just after installation

### ISSUE THREAD

**Issue by promeneur** [mozilla-lockwise/lockwise-android#556] opened 2019-03-28 17:42 UTC
Samsung S2 Plus, android 7.1.1, FF 66.0.2, lockbox 1.0, no fingerprint device
Samsung S7, android 8.0, FF 66.0.2, lockbox 1.0, fingerprint device
PC, FF 66.0.1
all FFs are synchronized.
all lockboxs are connected with success to the account
in the 2 cases after installation i click on button "finish" then synchronization begins then i get "No entries Found"

**Comment by promeneur** [comment] 2019-03-30 14:33
I got also the message "no network".

Sometime when i click on "finish" nothing happens.

**Comment by promeneur** [comment] 2019-03-30 14:33
Disconnecting fails

**Comment by abodea** [comment] 2019-07-29 08:59
Hi @promeneur thanks for this report.
I was not able to reproduce this issue on the latest version of Lockwise 1.1.3 (Build 4584) using Samsung Galaxy s10+(Android 9).
Can you please re-check with the latest version and provide some more info?

**Comment by promeneur** [comment] 2019-07-29 09:25
lockwise 1.1.2 problem still there. "No entries Found"

lockwise 1.1.3 not yet supplied by google play store.

if you go to https://play.google.com/store/apps/details?id=mozilla.lockbox
then
you read 

Mise à jour
1 juillet 2019

Version actuelle
1.1.1

strange !

**Comment by promeneur** [comment] 2019-07-31 11:06
lockwise 1.1.3

problem still there with a second message : "délai de synchronisation dépassé" (synchronization time exceeded)

i assume sync is well executed because : cache 564 MB  , data 641 MB

**Comment by abodea** [comment] 2019-07-31 13:15
@eliserichards any thoughts why this can happen? I tried with new accounts and old accounts but I couldn't reproduce it.
@promeneur can you please try with a fresh account to reproduce this issue?(only if possible).

**Comment by eliserichards** [comment] 2019-09-17 23:47
Hi @promeneur! I'm not able to reproduce this. Are you still seeing this?

**Comment by promeneur** [comment] 2019-09-18 06:24
Problem still there.

**Comment by promeneur** [comment] 2019-09-18 06:29
how to create another account? You need another mail address?

**Comment by promeneur** [comment] 2019-09-24 04:58
Lockwize 2.0.0 build 4831
no more problem with my s7 Android 8.0 and s2 plus android 7.1.2

thanks

**Comment by abodea** [comment] 2019-09-24 07:10
Thanks @promeneur for the feedback!
Based on your comment I will close this issue. If you will ever have any issues please do not hesitate to open a bug. 

Thanks,
Andrei

**Closed by abodea** 2019-09-24 07:10 UTC
Labels: CNR ⛔, blocked, feature-sync ♻️, question, type: defect
