### ISSUE TITLE
Consistently see a "null" toast message in new Android

### ISSUE THREAD

**Issue by ajjensen13** [mozilla-lockwise/lockwise-android#1237] opened 2020-11-01 14:56 UTC
## Steps to reproduce
Install Lockwise on a Pixel 4 running Android 11 (other models may be affected)

### Expected behavior
Whenever the gboard keyboard is opened, a "null" toast message does NOT appear

### Actual behavior
Whenever the gboard keyboard is opened, a "null" toast message DOES appear

![Screenshot_20201101-085506](https://user-images.githubusercontent.com/3858065/97806181-fed70380-1c1f-11eb-8fb4-56303f5592b6.png)

### Device & build information

![Screenshot_20201101-084849](https://user-images.githubusercontent.com/3858065/97806159-d8b16380-1c1f-11eb-9671-637d039d4fbf.png)

### Notes
It seems to only affect certain apps, or perhaps certain situations. I can consistently reproduce it when using the Android Messages app.

**Comment by Webbeh** [comment] 2020-11-01 14:58
#1224

**Comment by Webbeh** [comment] 2020-11-15 16:43
https://github.com/mozilla-lockwise/lockwise-android/issues/1219#issuecomment-727525094
Self-signed APK including the fix.

**Comment by Cubox** [comment] 2020-11-17 15:03
This issue should be closed as duplicate of #1219

**Comment by jrmuizel** [comment] 2020-12-08 17:22
It looks like #1219 has still not shipped though.

**Comment by abodea** [comment] 2020-12-10 14:10
Verified as fixed on the latest version **`4.0.2`** with **Google Pixel 4 XL (Android 11).**
Note that I tried with many apps but I couldn't reproduce it anymore.
I tried with the Android messages app, but everything worked as expected and no `Null` toast was displayed.
@ajjensen13 can you also, take a look, please?
Tested with Instagram, Latest Fenix Beta, Nightly, RC, Android messages app, Facebook, Twitter, and many other apps.

**Closed by abodea** 2020-12-10 14:10 UTC
Labels: defect

**Comment by ajjensen13** [comment] 2020-12-10 14:23
Confirmed I'm running version 4.0.2 and I cannot reproduce the issue. Thanks everyone who worked on this fix!

**Comment by abodea** [comment] 2020-12-10 14:34
Thank you for the confirmation @ajjensen13!!
