### ISSUE TITLE
Tapping in text-box from "Provide Feedback" module send the user to "All Logins" screen

### ISSUE THREAD

**Issue by Diana-Rus** [mozilla-lockwise/lockwise-android#780] opened 2019-06-26 08:51 UTC
## Steps to reproduce
1. Login in with a firefox account.
2. Go to "Settings"/"Provide Feedback" module.
3. In "Provide Feedback" screen go to point 4.
4. Tap in the text-box.

### Expected behavior
The user can add feedback into the text-box.

### Actual behavior
"All Logins" screen is displayed.

### Device & build information
* **`Device: Samsung Galaxy S8+(Android 8.0.0)`**
* **`Build version: Lockwise version 1.1.2 (Build 4342)`**
### Notes
Attachments: Video attached.
[Lockwise-26062019-4342.zip](https://github.com/mozilla-lockwise/lockwise-android/files/3329140/Lockwise-26062019-4342.zip)

**Comment by yuvalwolf** [comment] 2019-06-28 15:19
Couldn't reproduce on Pixel, Android v9, Lockwise Version 1.1.2 (4405)

**Comment by yuvalwolf** [comment] 2019-07-02 22:32
I was able to reproduce this behavior using the steps above on Pixel 3, Android v9, Lockwise v1.1.2 (4405)

**Comment by AndiAJ** [comment] 2019-07-29 08:11
Hi, this seems to be happening only by pressing the "Provide Feedback" button as per the attached video on Lockwise 1.1.3 (Build 4584) using a Google Pixel 3XL (Android 9) phone.
►[Video](https://drive.google.com/open?id=1dl8tQpxrLRc5hwSAcT5o2AAR0XV6-ktS)

### Not reproducible 100% happens occasionally.

**Comment by eliserichards** [comment] 2019-08-23 15:37
Closing in favor of #798 .

**Closed by eliserichards** 2019-08-23 15:37 UTC
Labels: P2, bug, closed-duplicate
