### ISSUE TITLE
Sutck on Unlock on ChromeOS 

### ISSUE THREAD

**Issue by anddam** [mozilla-lockwise/lockwise-android#693] opened 2019-05-22 19:50 UTC
I'm using Lockbox for Android as a way of migrating from Firefox (that has been my daily driver for several years) to Chrome on ChromeOS.

This is handier than starting regular Firefox for Linux into Crostini and accessing the saved logins there, mostly because Lockbox is focused at this very task. 

The ChromeOS Android compatibility layer does not have a way to set password, gesture, or PIN to unlock the emulated device.

Even setting Lockbox "auto-lock" setting to "never" after a reboot I find Lockbox locked, asking to be unlocked with the "UNLOCK" button. Pressing the unlock button yields no result.

 

Why is Lockbox locking even if its settings say to never auto-lock?

Is there a workaround to force the unlock or to prevent the locking to happen in first place?

**Comment by sandysage** [comment] 2019-05-29 15:33
Closing as a likely duplicate of #702

**Closed by sandysage** 2019-05-29 15:33 UTC
Labels: bug, 🔓 feature-unlocking
