### ISSUE TITLE
Add the possibility to multi-select accounts on the home screen

### ISSUE THREAD

**Issue by abodea** [mozilla-lockwise/lockwise-android#1173] opened 2020-02-18 08:55 UTC
### Why/User Benefit/User Problem
As a Lockwise user, I want to be able to multi-select accounts in case I wanna delete more at once. 
If categories will be implemented this will help to move the accounts easier.
### Acceptance Criteria (how do I know when I’m done?)
More accounts can be selected on the home screen.

**Comment by eliserichards** [comment] 2020-02-18 22:13
Close as dupe of #1172

**Closed by eliserichards** 2020-02-18 22:13 UTC
Labels: closed-duplicate, enhancement
