### ISSUE TITLE
Edit View: app is closed when saving or deleting an entry from this view

### ISSUE THREAD

**Issue by isabelrios** [mozilla-lockwise/lockwise-android#903] opened 2019-09-05 08:05 UTC
## Steps to reproduce
Open one entry
Tap on hamburger menu -> Edit
1-Do some changes and tap on Done button or 2-Tap on Delete Entry
### Expected behavior
1-The changes are saved successfully
2-The entry is correctly removed and I guess user is taken back to ListView but the app should not be closed
### Actual behavior
The app is closed
### Device & build information
* Device: Simulator, Pixel 3, API 28
* Build version: latest master b07e16187d1ac799ef54ef3dc4206232d3f47448
### Notes
Attachments:

**Comment by eliserichards** [comment] 2019-09-05 21:12
Known issue. Related to #798

**Comment by isabelrios** [comment] 2019-09-10 10:29
I can't reproduce this issue anymore. Now when the entry is modified and tapping on save button the ListView is shown with the entry updated. 
I guess that's the correct behaviour, right @eliserichards?

**Comment by eliserichards** [comment] 2019-09-18 15:12
I can't reproduce this anymore either :) Closing this issue.

**Closed by eliserichards** 2019-09-18 15:12 UTC
Labels: effort: XS, feature-edit ✏️, type: defect
