### ISSUE TITLE
Update Confirmation for Non-Biometric Devices

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockwise/lockwise-android#652] opened 2019-05-06 19:13 UTC
In instances where a user has a device that does not have biometrics, we shouldn't display the tout around unlocking with fingerprints...

Approach TBD: either remove the tout or replace it with something else

![Onboarding Confirmation](https://user-images.githubusercontent.com/6164801/57248879-c2aded00-7000-11e9-8d5c-eee11e8096a9.png)

**Comment by eliserichards** [comment] 2019-09-18 02:48
Duplicate of #543

**Closed by eliserichards** 2019-09-18 02:48 UTC
Labels: feature, feature-onboarding 🏁
